services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tododb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d tododb"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:4
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations:ro
    command: [
      "-path", "/migrations",
      "-database", "postgres://root:123456@db:5432/tododb?sslmode=disable",
      "up"
    ]
    restart: "on-failure"

  app:
    build: .
    environment:
      CONFIG_PATH: "/app/configs/config.json"
      DB_DRIVER: "postgres"
      DS_NAME: "postgres://root:123456@db:5432/tododb?sslmode=disable"
    volumes:
        - ./configs:/app/configs:ro
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  db_data:
